from __future__ import annotations

from litestar import (
    post,
)
from litestar.connection import Request
from litestar.exceptions import (
    ClientException,
    NotAuthorizedException,
)
from litestar.response import Response
from sqlalchemy.ext.asyncio import (
    AsyncSession,
)

from app.api.routes.auth_cookies import set_auth_cookies
from app.domain.audit.service import log_audit_event
from app.domain.auth.exceptions import (
    AuthenticationError,
    InvalidMFAChallengeError,
    InvalidMFACodeError,
)
from app.domain.auth.mfa import (
    MFAService,
)
from app.domain.database.models.user import (
    User,
)
from app.schemas.requests.mfa import (
    MFADisableRequest,
    MFALoginRequest,
    MFAVerifyRequest,
)
from app.schemas.responses.auth import (
    AuthUserResponse,
)
from app.schemas.responses.mfa import (
    MFALoginResponse,
    MFASetupResponse,
    MFAVerifyResponse,
)

mfa = MFAService()


@post(
    path="/auth/mfa/setup",
    operation_id="setupMfa",
    summary="Setup MFA For User",
    description="This Route Generates A Time-Based One-Time Password (TOTP) Provisioning URI For The Authenticated User. The URI Can Be Used To Configure An Authenticator App Such As Google Authenticator Or Authy.",
    tags=["Multi-Factor Authentication"],
)
async def setup_mfa(
    request: Request,
    database_session: AsyncSession,
    authenticated_user: User,
) -> MFASetupResponse:
    try:
        setup_result = await mfa.setup_mfa(
            database_session=database_session,
            user=authenticated_user,
        )

    except AuthenticationError as error:
        raise (ClientException(str(error))) from error

    await log_audit_event(
        database_session=database_session,
        action="mfa.setup",
        actor_id=authenticated_user.id,
        resource_type="mfa",
        resource_id=authenticated_user.id,
        ip_address=request.client.host if request.client else None,
        user_agent=request.headers.get("user-agent"),
    )

    return MFASetupResponse(
        provisioning_uri=setup_result.provisioning_uri,
        mfa_enabled=setup_result.mfa_enabled,
    )


@post(
    path="/auth/mfa/verify",
    operation_id="verifyMfa",
    summary="Verify MFA Setup",
    description="This Route Confirms That Multi-Factor Authentication Has Been Successfully Configured By Validating A TOTP Code Generated By The User Authenticator App. On Success, Enables MFA For The User Account.",
    tags=["Multi-Factor Authentication"],
)
async def verify_mfa(
    request: Request,
    data: MFAVerifyRequest,
    database_session: AsyncSession,
    authenticated_user: User,
) -> MFAVerifyResponse:
    try:
        await mfa.verify_mfa_setup(
            database_session=database_session,
            user=authenticated_user,
            code=data.code,
        )

    except InvalidMFACodeError as error:
        raise (NotAuthorizedException(str(error))) from error

    except AuthenticationError as error:
        raise (ClientException(str(error))) from error

    await log_audit_event(
        database_session=database_session,
        action="mfa.verify",
        actor_id=authenticated_user.id,
        resource_type="mfa",
        resource_id=authenticated_user.id,
        details={"mfa_enabled": True},
        ip_address=request.client.host if request.client else None,
        user_agent=request.headers.get("user-agent"),
    )

    return MFAVerifyResponse(
        success=True,
        mfa_enabled=True,
    )


@post(
    path="/auth/mfa/login",
    operation_id="loginWithMfa",
    summary="Complete Login With MFA",
    description="This Route Completes The Multi-Factor Authentication Flow After An Initial Login Challenge. Validates The Temporary Token And TOTP Code, Then Returns Full Authentication Tokens And Sets HttpOnly Cookies On Success.",
    tags=["Multi-Factor Authentication"],
)
async def login_with_mfa(
    request: Request,
    data: MFALoginRequest,
    database_session: AsyncSession,
) -> Response[MFALoginResponse]:
    try:
        authentication_result = await mfa.complete_mfa_login(
            database_session=database_session,
            temporary_token=data.temporary_token,
            code=data.code,
        )

    except (InvalidMFAChallengeError, InvalidMFACodeError) as error:
        raise (NotAuthorizedException(str(error))) from error

    except AuthenticationError as error:
        raise (ClientException(str(error))) from error

    response = Response(
        MFALoginResponse(
            user=(
                AuthUserResponse(
                    id=authentication_result.user.id,
                    name=authentication_result.user.name,
                    username=authentication_result.user.username,
                    avatar_url=authentication_result.user.avatar_url,
                )
            ),
            mfa_enabled=True,
        )
    )

    set_auth_cookies(
        response,
        access_token=authentication_result.access_token,
        refresh_token=authentication_result.refresh_token,
    )

    await log_audit_event(
        database_session=database_session,
        action="mfa.login",
        actor_id=authentication_result.user.id,
        resource_type="mfa",
        resource_id=authentication_result.user.id,
        ip_address=request.client.host if request.client else None,
        user_agent=request.headers.get("user-agent"),
    )

    return response


@post(
    path="/auth/mfa/disable",
    operation_id="disableMfa",
    summary="Disable MFA For User",
    description="This Route Disables Multi-Factor Authentication For The Authenticated User After Validating Their Current TOTP Code. Requires The User To Confirm They Have Access To Their Authenticator App Before Proceeding.",
    tags=["Multi-Factor Authentication"],
)
async def disable_mfa(
    request: Request,
    data: MFADisableRequest,
    database_session: AsyncSession,
    authenticated_user: User,
) -> MFAVerifyResponse:
    try:
        await mfa.disable_mfa(
            database_session=database_session,
            user=authenticated_user,
            code=data.code,
        )

    except InvalidMFACodeError as error:
        raise (NotAuthorizedException(str(error))) from error

    except AuthenticationError as error:
        raise (ClientException(str(error))) from error

    await log_audit_event(
        database_session=database_session,
        action="mfa.disable",
        actor_id=authenticated_user.id,
        resource_type="mfa",
        resource_id=authenticated_user.id,
        details={"mfa_enabled": False},
        ip_address=request.client.host if request.client else None,
        user_agent=request.headers.get("user-agent"),
    )

    return MFAVerifyResponse(
        success=True,
        mfa_enabled=False,
    )
