from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate TypeScript types from OpenAPI component schemas."
    )
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def type_name(name: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not normalized or normalized[0].isdigit():
        normalized = f"Schema_{normalized}"
    return normalized


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return type_name(str(schema["$ref"]).rsplit("/", 1)[-1])

    if "anyOf" in schema:
        return " | ".join(ts_type(item) for item in schema["anyOf"])

    if "oneOf" in schema:
        return " | ".join(ts_type(item) for item in schema["oneOf"])

    enum_values = schema.get("enum")
    if isinstance(enum_values, list):
        return " | ".join(json.dumps(value) for value in enum_values)

    if schema.get("nullable") is True:
        return f"{ts_type({key: value for key, value in schema.items() if key != 'nullable'})} | null"

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(
            "null" if item == "null" else ts_type({**schema, "type": item})
            for item in schema_type
        )

    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required") or [])
        if not properties:
            return "Record<string, unknown>"
        fields = []
        for key, value in sorted(properties.items()):
            field_type = ts_type(value)
            if key not in required and "null" not in field_type:
                field_type = f"{field_type} | null"
            fields.append(
                f"{json.dumps(key)}{'' if key in required else '?'}: {field_type};"
            )
        return "{ " + " ".join(fields) + " }"
    if schema.get("const") is not None:
        return json.dumps(schema["const"])
    return "unknown"


def main() -> None:
    args = parse_args()
    contract = json.loads(args.input.read_text(encoding="utf-8"))
    schemas = contract.get("components", {}).get("schemas", {})

    lines = [
        "// Generated by backend/scripts/export_openapi_types.py. Do not edit manually.",
        "",
    ]
    for name, schema in sorted(schemas.items()):
        lines.append(f"export type {type_name(name)} = {ts_type(schema)};")
        lines.append("")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
