DEFAULT_ALIGNMENT_WORD_DELIMITER = "|"

DEFAULT_ALIGNMENT_FLOAT_DTYPE = "float32"

DEFAULT_ALIGNMENT_QUANTIZATION_BACKEND = "torchao"

SUPPORTED_ALIGNMENT_QUANTIZATION_BACKENDS = (
    "torchao",
    "onnxruntime",
)

SUPPORTED_ALIGNMENT_QUANTIZATION_PRECISIONS = (
    "int8",
    "int4",
    "fp8",
)
